project:
  type: website
  output-dir: docs

website:
  title: "ml-project"
  navbar:
    left:
      - href: 20250722.ipynb
        text: Exercise
      - href: project1.ipynb
        text: Project1
      - href: project2.ipynb
        text: Project2

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



